version: '3'

services:
###> doctrine/doctrine-bundle ###
  php:
      build:
          context: .
          dockerfile: docker/php/Dockerfile
          args:
              TIMEZONE: ${TIMEZONE}
      container_name: psqls6_php2
      volumes:
          - .:/var/www/webapp/
      networks:
          - symfony
  nginx:
      build:
          context: .
          dockerfile: docker/nginx/Dockerfile
      container_name: psqls6_nginx2
      volumes:
          - .:/var/www/webapp/
      ports:
          - 80:80
      networks:
          - symfony
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - symfony
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
networks:
    symfony: